dbms: postgres # mysql, mongo
dbConfig:
  host: localhost
  port: 5432
  user: root
  password: password
  dbname: defaultdb
backupStorage: local
storage:
  accessKey: akey
  privateAccessKey: pakey
  path: /path/to/backup